apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol103
spec:
  capacity:
    storage: 500Gi 
  accessModes:
    - ReadWriteOnce     
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/data/vol103
